### ISSUE TITLE
System Error, and Fatal error detected

### ISSUE THREAD

**Issue by mutsurhea** [shirokumacode/overwatch-omnic-rewards#17]
i just downloaded the [omnic_rewards_Windows.exe](https://github.com/shirokumacode/overwatch-omnic-rewards/releases/download/v1.3/omnic_rewards_Windows.exe)

when i try to run on Windows 7 i first get a popup

> > omnic_rewards_Windows.exe - System Error

> The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem

i click OK, then

> > Fatal error detected

> Error loading Python DLL
> \C:\Users\user\AppData\Local\Temp\_MEI157722\python310.dll',
> LoadLibrary: The specified module could not be found.

[images](https://imgur.com/a/08owVkb)

what do i do?

**Comment by mutsurhea** [comment]
someone suggested i install [python 3.10](https://www.python.org/downloads/release/python-3100/)

but i am unable to do so

> > Setup failed

> At least W8.1 required

![image](https://user-images.githubusercontent.com/77935124/170732997-df03359c-e897-4568-9e69-5de09164ae4a.png)

**Comment by shirokumacode** [comment]
Python (latest versions) are currently unsupported in Windows 7 (as Microsoft no longer supports it). This project requires at least Python 3.9, which is not supported in Windows 7.  Please update to a OS version that Microsoft is actively supporting (Python follows that).

Note:
Installing Python does not solve this issue as the executable already includes Python inside and will use that. There is no point in installing the required DLL's from your error manually because you will eventually be going in circles with other errors. Only real solution is to run the app with an older version of Python and do the necessary code rewrites that it would need.

**Comment by mutsurhea** [comment]
well im a little disappointed in the anwer
but still happy you replied.
