### ISSUE TITLE
Checker HTTP error - 500

### ISSUE THREAD

**Issue by Alomare** [shirokumacode/overwatch-omnic-rewards#21]
![image](https://user-images.githubusercontent.com/86606696/171227337-29a8293d-3f63-40a5-b231-17a606686294.png)
Checking and restarting did not fix the issue.

**Comment by shirokumacode** [comment]
Working on it. Expect a new version today or tomorrow. However this shouldn't affect when the stream goes live, hopefully.

OWL League website added a banner to their page at the top (Dallas Fuel kickoff clash tournament) and that's probably what's tripping that error and an earlier one on the page being badly formatted. I didn't do the best job (I did the quick one, hoping it wouldn't break) when coding the section of getting the correct html element.

**Comment by shirokumacode** [comment]
As soon I started working on this, the app now works properly. Overwatch league website no longer responds with a HTTP error and the previous errors about the incorrectly formatted page are gone, even with the new banner. Probably Blizzard fixed whatever was wrong.
I initially thought they changed the format of the website and I had to adapt the app again, but I guess this was not intentional. On the overwatch league website there is section (only visible when live, but it is always there) for the video panel that this app relies on. If this section does not exist or if the website sends a bad html code, this app show the appropriate error. 
Closing this for now
