### ISSUE TITLE
User ID problem

### ISSUE THREAD

**Issue by github59173** [shirokumacode/overwatch-omnic-rewards#9]
In preparation for the upcoming Overwatch League season I wanted to get this setup for an account but was unable to get the User ID from the link provided in the program; error 404 page not found (either was removed or moved to a new location on the site).

**Comment by shirokumacode** [comment]
I guess Blizzard removed that page. It sucks because that was the easiest way and also really straightforward to get your Battle.net account ID. There are other ways to get your account ID, some almost as easy, some harder. 

Currently this app is in a limbo until the new season of Overwatch League starts. I am hesitant to patch stuff now because if they change anything in this new season it might make my current work useless. Hopefully they will only make minor changes and nothing major that breaks this app. Nevertheless I will fix this and any other issue when the new season begins.

Meanwhile, if you really need to, you can workaround this issue:
Follow the instructions on the app but instead of going to [https://www.blizzard.com/user](https://www.blizzard.com/user) go to [https://www.blizzard.com/navbar/authenticate](https://www.blizzard.com/navbar/authenticate) while logged in. You should see your Battle.net account ID number marked as id. Should be the first item and is a number. 
If you have any trouble with this don't hesitate to reply.

**Comment by shirokumacode** [comment]
Fixed in version 1.3
